# Generated by Django 3.0.11 on 2021-01-12 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('reg_id', models.IntegerField(unique=True)),
                ('level', models.SmallIntegerField(default=1)),
                ('remarks', models.TextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Department')),
                ('plan', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Plan')),
            ],
        ),
        migrations.DeleteModel(
            name='Student3',
        ),
    ]
