# Generated by Django 3.0.11 on 2021-01-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210112_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='plan',
        ),
        migrations.AddField(
            model_name='plan',
            name='modules',
            field=models.ManyToManyField(to='core.Module'),
        ),
        migrations.AddField(
            model_name='student',
            name='credits',
            field=models.SmallIntegerField(default=0),
        ),
    ]
