# Generated by Django 3.0.11 on 2021-01-12 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210112_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='pre_module',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_module', to='core.Module'),
        ),
    ]
